'use strict';
const $=s=>document.querySelector(s), t=(k,v)=>window.realityI18n.t(k,v);
let profiles=[],subscriptions=[],selectedProfileID=null,connection={state:'disconnected',profile:null},corePath='',logs=[],latencies={},testing=false;
const collapsed=new Set(), stateKeys={disconnected:'未连接',connecting:'connecting',connected:'connected',switching:'switching',disconnecting:'disconnecting',failed:'failed'};
const selected=()=>profiles.find(p=>p.id===selectedProfileID), busy=()=>['connecting','switching','disconnecting'].includes(connection.state);
async function api(action,target=$('#errorMessage')){try{target.textContent='';return await action();}catch(e){target.textContent=e.message.replace(/^Error invoking remote method '[^']+': Error: /,'');return null;}}
function profileButton(p){const b=document.createElement('button');b.className=`profile ${p.id===selectedProfileID?'selected':''} ${connection.profile?.id===p.id&&['connected','switching'].includes(connection.state)?'active':''}`;const dot=document.createElement('span');dot.className='dot';const body=document.createElement('div'),name=document.createElement('b'),meta=document.createElement('small'),lat=document.createElement('span');name.textContent=p.name;meta.textContent=`${(p.proxyProtocol||'vless').toUpperCase()} · ${p.server}:${p.port}`;lat.className=`latency ${latencies[p.id]==null?'unavailable':''}`;lat.textContent=latencies[p.id]===undefined?'—':latencies[p.id]===null?'×':`${latencies[p.id]} ms`;body.append(name,meta);b.append(dot,body,lat);b.onclick=async()=>{selectedProfileID=p.id;await api(()=>window.realityLink.selectProfile(p.id));render();};return b;}
function group(title,items,subscription){const wrap=document.createElement('section');wrap.className='profile-group';const head=document.createElement('div');head.className='group-head';const fold=document.createElement('button');fold.className='group-toggle';fold.textContent=`${collapsed.has(title)?'▸':'▾'} ${title} (${items.length})`;fold.onclick=()=>{collapsed.has(title)?collapsed.delete(title):collapsed.add(title);render();};head.append(fold);if(subscription){const renew=document.createElement('button');renew.className='group-action';renew.textContent='↻';renew.title=t('renew');renew.onclick=()=>renewGroup(subscription);const del=document.createElement('button');del.className='group-action';del.textContent='×';del.title=t('deleteSubscription');del.onclick=()=>deleteGroup(subscription);head.append(renew,del);}wrap.append(head);if(!collapsed.has(title))items.forEach(p=>wrap.append(profileButton(p)));return wrap;}
function render(){const box=$('#profiles');box.replaceChildren();subscriptions.forEach(s=>box.append(group(s.name,profiles.filter(p=>p.subscriptionID===s.id),s)));const local=profiles.filter(p=>!p.subscriptionID);if(local.length||!subscriptions.length)box.append(group(t('localNodes'),local));$('#nodeCount').textContent=t('nodes',profiles.length);const p=selected(),card=$('#profileCard');if(!p){card.className='card empty';card.textContent=t('empty');}else{card.className='card';card.replaceChildren();const head=document.createElement('div');head.className='card-head';const title=document.createElement('h2');title.textContent=p.name;const actions=document.createElement('div');actions.className='card-actions';const test=document.createElement('button');test.className='ghost';test.textContent=t('latencyTest');test.onclick=()=>testLatency([p.id]);const edit=document.createElement('button');edit.className='ghost';edit.textContent=t('edit');edit.disabled=Boolean(p.subscriptionID);edit.onclick=()=>openEditor(p);const del=document.createElement('button');del.className='ghost';del.textContent=t('delete');del.disabled=Boolean(p.subscriptionID)||!['disconnected','failed'].includes(connection.state);del.onclick=()=>deleteProfile(p);actions.append(test,edit,del);head.append(title,actions);const grid=document.createElement('div');grid.className='card-grid';[[t('protocol'),(p.proxyProtocol||'vless').toUpperCase()],[t('服务器'),`${p.server}:${p.port}`],[t('security'),p.security||t('none')],[t('transport'),p.transport||'tcp'],[t('latency'),latencies[p.id]===undefined?t('notTested'):latencies[p.id]===null?t('timeout'):`${latencies[p.id]} ms`]].forEach(([k,v])=>{const a=document.createElement('span'),b=document.createElement('span');a.textContent=k;b.textContent=v;grid.append(a,b);});card.append(head,grid);}$('#statusTitle').textContent=t(stateKeys[connection.state]||connection.state);$('#statusSubtitle').textContent=connection.state==='connected'?t('traffic',connection.profile?.name||'TUN'):connection.state==='switching'?t('switchingSubtitle'):connection.state==='connecting'?t('connectingSubtitle'):t('选择一个节点开始连接');$('#statusOrb').className=`status-orb ${connection.state==='connected'?'connected':busy()?'busy':connection.state==='failed'?'failed':''}`;const connect=$('#connectButton');connect.disabled=!p||busy();const active=connection.profile?.id===p?.id;connect.textContent=connection.state==='connected'?(active?t('disconnect'):t('switchTo')):t('connect');connect.className=connection.state==='connected'&&active?'primary danger':'primary';$('#latencyButton').disabled=testing||!profiles.length;$('#latencyButton').textContent=testing?'…':'◷';$('#logs').textContent=logs.join('\n');}
async function renewGroup(s){const result=await api(()=>window.realityLink.renewSubscription(s.id));if(result){profiles=result.profiles;subscriptions=result.subscriptions;selectedProfileID=result.selectedProfileID;render();}}
async function deleteGroup(s){if(!confirm(t('deleteSubscriptionConfirm',s.name)))return;const result=await api(()=>window.realityLink.deleteSubscription(s.id));if(result){profiles=result.profiles;subscriptions=result.subscriptions;selectedProfileID=result.selectedProfileID;render();}}
async function testLatency(ids){testing=true;render();const result=await api(()=>window.realityLink.testLatency(ids));if(result)Object.assign(latencies,result);testing=false;render();}
$('#connectButton').onclick=async()=>{const p=selected();if(!p)return;if(connection.state==='connected'){if(connection.profile?.id===p.id)await api(()=>window.realityLink.stop());else await api(()=>window.realityLink.switchProfile(p.id));}else await api(()=>window.realityLink.start(p.id));};
$('#importButton').onclick=()=>{$('#importURL').value='';$('#importDialog .dialogError').textContent='';$('#importDialog').showModal();};
$('#confirmImport').onclick=async e=>{e.preventDefault();const result=await api(()=>window.realityLink.importProfile($('#importURL').value),$('#importDialog .dialogError'));if(result){profiles=result.profiles;subscriptions=result.subscriptions;selectedProfileID=result.selectedProfileID;$('#importDialog').close();render();}};
$('#addButton').onclick=()=>openEditor();$('#latencyButton').onclick=()=>testLatency(profiles.map(p=>p.id));document.querySelectorAll('.storeButton').forEach(b=>b.onclick=()=>window.realityLink.openStore());
const fieldIDs=['proxyProtocol','name','server','port','uuid','password','security','transport','serverName','publicKey','shortID','fingerprint','flow','encryption','alterID','transportHost','transportPath','serviceName','alpn','obfuscation','obfuscationPassword','congestionControl','udpRelayMode'];
function syncFields(){const p=$('#proxyProtocol').value,s=$('#security').value,tr=$('#transport').value;const show={uuid:['vless','vmess','tuic'].includes(p),password:['trojan','shadowsocks','hysteria2','tuic'].includes(p),security:p!=='shadowsocks',transport:['vless','vmess','trojan'].includes(p),serverName:p!=='shadowsocks'&&s!=='none',publicKey:p==='vless'&&s==='reality',shortID:p==='vless'&&s==='reality',fingerprint:p!=='shadowsocks'&&s!=='none',flow:p==='vless'&&tr==='tcp',encryption:['vmess','shadowsocks'].includes(p),alterID:p==='vmess',transportHost:['vless','vmess','trojan'].includes(p)&&['ws','http'].includes(tr),transportPath:['vless','vmess','trojan'].includes(p)&&['ws','http'].includes(tr),serviceName:['vless','vmess','trojan'].includes(p)&&tr==='grpc',alpn:p!=='shadowsocks'&&s!=='none',obfuscation:p==='hysteria2',obfuscationPassword:p==='hysteria2'&&$('#obfuscation').value!=='',congestionControl:p==='tuic',udpRelayMode:p==='tuic',allowInsecure:p!=='shadowsocks'&&s!=='none'};document.querySelectorAll('[data-field]').forEach(el=>el.classList.toggle('field-hidden',!show[el.dataset.field]));}
function openEditor(p={}){const defaults={proxyProtocol:'vless',port:443,security:'reality',transport:'tcp',fingerprint:'chrome',encryption:'auto',alterID:0,congestionControl:'cubic',udpRelayMode:'native'};const v={...defaults,...p};$('#profileID').value=v.id||'';fieldIDs.forEach(id=>{$(`#${id}`).value=v[id]??'';});$('#allowInsecure').checked=Boolean(v.allowInsecure);$('#editorTitle').textContent=p.id?t('editNode'):t('添加节点');$('#profileDialog .dialogError').textContent='';syncFields();$('#profileDialog').showModal();}
['proxyProtocol','security','transport','obfuscation'].forEach(id=>$(`#${id}`).onchange=syncFields);
$('#confirmProfile').onclick=async e=>{e.preventDefault();const p={id:$('#profileID').value,allowInsecure:$('#allowInsecure').checked};fieldIDs.forEach(id=>p[id]=$(`#${id}`).value);const result=await api(()=>window.realityLink.saveProfile(p),$('#profileDialog .dialogError'));if(result){profiles=result.profiles;subscriptions=result.subscriptions;selectedProfileID=result.selectedProfileID;$('#profileDialog').close();render();}};
$('#settingsButton').onclick=()=>{$('#corePath').value=corePath;$('#languageSelect').value=window.realityI18n.current();$('#settingsDialog').showModal();};$('#languageSelect').onchange=()=>window.realityI18n.setLanguage($('#languageSelect').value);$('#confirmSettings').onclick=async e=>{e.preventDefault();corePath=$('#corePath').value.trim();await api(()=>window.realityLink.saveCorePath(corePath));$('#settingsDialog').close();};$('#clearLogs').onclick=()=>{logs=[];render();};document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===tab));$('#connectionTab').classList.toggle('hidden',tab.dataset.tab!=='connection');$('#logsTab').classList.toggle('hidden',tab.dataset.tab!=='logs');});
async function deleteProfile(p){if(!confirm(t('deleteConfirm',p.name)))return;const r=await api(()=>window.realityLink.deleteProfile(p.id));if(r){profiles=r.profiles;subscriptions=r.subscriptions;selectedProfileID=r.selectedProfileID;render();}}
window.realityLink.onStatus(v=>{connection=v;render();});window.realityLink.onLogs(lines=>{logs.push(...lines);logs=logs.slice(-1000);render();$('#logs').scrollTop=$('#logs').scrollHeight;});window.realityI18n.onChange(render);window.realityLink.getInitialState().then(s=>{profiles=s.profiles;subscriptions=s.subscriptions||[];selectedProfileID=s.selectedProfileID;corePath=s.corePath;connection=s.connection;logs=s.connection.logs||[];render();});
