'use strict';
const { parseProxy }=require('./profile');
const schemes='(?:vless|vmess|trojan|ss|hysteria2|hy2|tuic)';
function decode64(value){try{return Buffer.from(String(value).replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8');}catch{return'';}}
function subscriptionURL(input){const raw=String(input||'').trim();const candidates=[];if(/^https?:\/\//i.test(raw))candidates.push(raw);else if(/^sub:\/\//i.test(raw)){const payload=raw.slice(6).split('#')[0];candidates.push(decodeURIComponent(payload),decode64(decodeURIComponent(payload)),decode64(payload));}for(const value of candidates){try{const url=new URL(value.trim());if(['http:','https:'].includes(url.protocol)&&url.hostname)return url;}catch{}}throw new Error('订阅链接无效，仅支持 sub:// 和 HTTP(S)');}
function parseDocument(buffer){if(buffer.length>2*1024*1024)throw new Error('订阅内容超过 2 MB');const text=buffer.toString('utf8');const documents=[text,decode64(text.replace(/\s/g,''))];const found=[];for(const document of documents){for(const match of document.matchAll(new RegExp(`${schemes}:\\/\\/[^\\s"'<>]+`,'gi'))){try{found.push(parseProxy(match[0].replace(/[,;\]}]+$/,'')));}catch{}}}const seen=new Set();return found.filter(p=>{const key=[p.proxyProtocol,p.server,p.port,p.uuid||p.password,p.security,p.transport,p.transportPath,p.serviceName].join('|');if(seen.has(key))return false;seen.add(key);return true;});}
async function fetchSubscription(input){const url=subscriptionURL(input);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(url,{redirect:'follow',signal:controller.signal,headers:{'User-Agent':'RealityLink/0.2.0','Accept':'text/plain, application/octet-stream, */*'}});if(!response.ok)throw new Error(`订阅服务器返回 HTTP ${response.status}`);const data=Buffer.from(await response.arrayBuffer());const profiles=parseDocument(data);if(!profiles.length)throw new Error('订阅中没有可兼容的代理节点');return profiles;}finally{clearTimeout(timer);}}
function groupName(input){const url=subscriptionURL(input);return decodeURIComponent(url.pathname.split('/').filter(Boolean).pop()||url.hostname);}
module.exports={subscriptionURL,parseDocument,fetchSubscription,groupName};
