import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case chinese = "zh-Hans"
    case russian = "ru"

    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .english: "English"
        case .chinese: "中文"
        case .russian: "Русский"
        }
    }
}

enum L10n {
    static func t(_ key: String, _ language: AppLanguage, _ arguments: CVarArg...) -> String {
        let template = strings[language]?[key] ?? strings[.english]?[key] ?? key
        guard !arguments.isEmpty else { return template }
        return String(format: template, locale: Locale(identifier: language.rawValue), arguments: arguments)
    }

    private static let strings: [AppLanguage: [String: String]] = [
        .english: [
            "language": "Language",
            "settings": "Settings",
            "core": "sing-box core",
            "customPath": "Custom path",
            "corePrompt": "Find Homebrew path automatically",
            "coreHelp": "When empty, the bundled core, /opt/homebrew/bin and /usr/local/bin are checked in order.",
            "localProxy": "Local proxy",
            "listenPort": "Listen port",
            "proxyHelp": "System Proxy provides HTTP and SOCKS5 on 127.0.0.1 by default.",
            "importLink": "Import link",
            "addNode": "Add node",
            "edit": "Edit",
            "delete": "Delete",
            "nodesCount": "%d nodes",
            "localNodes": "Local nodes",
            "renewSubscription": "Update subscription",
            "deleteSubscription": "Delete subscription",
            "deleteSubscriptionTitle": "Delete this subscription?",
            "deleteSubscriptionAndNodes": "Delete Subscription and Nodes",
            "deleteSubscriptionHelp": "All nodes belonging to this subscription will also be removed.",
            "subscriptionUpdateFailed": "Subscription update failed",
            "testLatency": "Test latency",
            "testGroupLatency": "Test this group",
            "testLatencyHelp": "Measures direct TCP connection time through the physical network interface.",
            "buyNodes": "Buy nodes",
            "nodeStore": "Node service",
            "ok": "OK",
            "page": "Page",
            "connection": "Connection",
            "logs": "Logs",
            "noNodes": "No nodes yet",
            "noNodesHelp": "Import a supported proxy link or subscription, or enter node details manually.",
            "addManually": "Add manually",
            "server": "Server",
            "none": "None",
            "fingerprint": "Fingerprint",
            "protocol": "Protocol",
            "security": "Security",
            "transport": "Transport",
            "allowInsecure": "Allow insecure certificates",
            "transportHost": "Host header",
            "transportPath": "Path",
            "serviceName": "Service name",
            "password": "Password",
            "encryption": "Encryption",
            "obfuscation": "Obfuscation",
            "obfuscationPassword": "Obfuscation password",
            "congestionControl": "Congestion control",
            "udpRelayMode": "UDP relay mode",
            "connectionMode": "Connection mode",
            "systemProxy": "System Proxy",
            "tun": "Global TUN",
            "systemProxyDetail": "Covers apps that follow macOS proxy settings; restricted devices may request administrator authorization.",
            "tunDetail": "Routes most TCP/UDP traffic; after first authorization, switching and disconnecting do not ask for the password again.",
            "disconnected": "Disconnected",
            "connecting": "Connecting",
            "connected": "Connected",
            "switching": "Switching",
            "disconnecting": "Disconnecting",
            "failed": "Connection failed",
            "trafficThrough": "Traffic is routed through %@",
            "startingCore": "Starting the sing-box core",
            "switchingNode": "Keeping network settings while switching nodes",
            "cleaningNetwork": "Cleaning up network settings",
            "checkError": "Check the error below or open Logs",
            "readyToConnect": "Choose a mode and connect safely",
            "disconnect": "Disconnect",
            "switchToNode": "Switch to this node",
            "connect": "Connect",
            "basicInfo": "Basic information",
            "name": "Name",
            "port": "Port",
            "publicKey": "Public key (pbk)",
            "cancel": "Cancel",
            "save": "Save",
            "editNode": "Edit node",
            "importVLESS": "Import link or subscription",
            "importHelp": "Supports VLESS, VMess, Trojan, Shadowsocks, Hysteria2, and TUIC",
            "pasteClipboard": "Paste from Clipboard",
            "import": "Import",
            "importing": "Importing…",
            "subscriptionInvalid": "The subscription link is invalid or cannot be decoded.",
            "subscriptionScheme": "Only sub:// and HTTP(S) subscription links are supported.",
            "subscriptionHTTPError": "The subscription server returned HTTP %d.",
            "subscriptionTooLarge": "The subscription response is larger than 2 MB.",
            "subscriptionUnreadable": "The subscription response is not valid UTF-8 text.",
            "subscriptionNoNodes": "No compatible proxy nodes were found in this subscription.",
            "runtimeLogs": "Runtime logs",
            "clear": "Clear",
            "noLogs": "No logs yet",
            "noLogsHelp": "Core output will appear here after you connect.",
            "openApp": "Open RealityLink",
            "quit": "Quit",
            "disconnectQuit": "Disconnect and Quit",
            "addNodeFirst": "Add a node first",
            "switchToNamed": "Switch to %@",
            "connectNamed": "Connect %@"
        ],
        .chinese: [
            "language": "语言",
            "settings": "设置",
            "core": "sing-box 内核",
            "customPath": "自定义路径",
            "corePrompt": "自动查找 Homebrew 路径",
            "coreHelp": "留空时依次查找 App 内置内核、/opt/homebrew/bin 和 /usr/local/bin。",
            "localProxy": "本地代理",
            "listenPort": "监听端口",
            "proxyHelp": "系统代理模式同时提供 HTTP 和 SOCKS5，默认仅监听 127.0.0.1。",
            "importLink": "导入链接",
            "addNode": "添加节点",
            "edit": "编辑",
            "delete": "删除",
            "nodesCount": "%d 个节点",
            "localNodes": "本地节点",
            "renewSubscription": "更新订阅",
            "deleteSubscription": "删除订阅",
            "deleteSubscriptionTitle": "删除这个订阅？",
            "deleteSubscriptionAndNodes": "删除订阅及其节点",
            "deleteSubscriptionHelp": "属于这个订阅的所有节点也会一起删除。",
            "subscriptionUpdateFailed": "订阅更新失败",
            "testLatency": "测试延迟",
            "testGroupLatency": "测试此分组",
            "testLatencyHelp": "通过物理网卡直接测试每个节点的 TCP 建连时间。",
            "buyNodes": "购买节点",
            "nodeStore": "节点服务",
            "ok": "确定",
            "page": "页面",
            "connection": "连接",
            "logs": "日志",
            "noNodes": "还没有节点",
            "noNodesHelp": "导入支持的代理链接或订阅，或手动填写节点参数。",
            "addManually": "手动添加",
            "server": "服务器",
            "none": "无",
            "fingerprint": "指纹",
            "protocol": "协议",
            "security": "安全类型",
            "transport": "传输方式",
            "allowInsecure": "允许不安全证书",
            "transportHost": "Host 请求头",
            "transportPath": "路径",
            "serviceName": "服务名称",
            "password": "密码",
            "encryption": "加密方式",
            "obfuscation": "混淆",
            "obfuscationPassword": "混淆密码",
            "congestionControl": "拥塞控制",
            "udpRelayMode": "UDP 转发模式",
            "connectionMode": "连接模式",
            "systemProxy": "系统代理",
            "tun": "全局 TUN",
            "systemProxyDetail": "覆盖遵循 macOS 代理设置的应用；受限设备会要求管理员授权。",
            "tunDetail": "接管大多数 TCP/UDP 流量；首次连接授权后，切换和断开无需再次输入密码。",
            "disconnected": "未连接",
            "connecting": "正在连接",
            "connected": "已连接",
            "switching": "正在切换",
            "disconnecting": "正在断开",
            "failed": "连接失败",
            "trafficThrough": "流量正在通过 %@",
            "startingCore": "正在启动 sing-box 内核",
            "switchingNode": "保持系统网络设置，正在切换节点",
            "cleaningNetwork": "正在清理网络设置",
            "checkError": "请查看下方错误或日志",
            "readyToConnect": "选择模式后即可安全连接",
            "disconnect": "断开连接",
            "switchToNode": "切换到此节点",
            "connect": "连接",
            "basicInfo": "基本信息",
            "name": "名称",
            "port": "端口",
            "publicKey": "公钥 (pbk)",
            "cancel": "取消",
            "save": "保存",
            "editNode": "编辑节点",
            "importVLESS": "导入链接或订阅",
            "importHelp": "支持 VLESS、VMess、Trojan、Shadowsocks、Hysteria2 和 TUIC",
            "pasteClipboard": "从剪贴板粘贴",
            "import": "导入",
            "importing": "正在导入…",
            "subscriptionInvalid": "订阅链接无效或无法解码。",
            "subscriptionScheme": "仅支持 sub:// 和 HTTP(S) 订阅链接。",
            "subscriptionHTTPError": "订阅服务器返回 HTTP %d。",
            "subscriptionTooLarge": "订阅内容超过 2 MB。",
            "subscriptionUnreadable": "订阅内容不是有效的 UTF-8 文本。",
            "subscriptionNoNodes": "订阅中没有可兼容的代理节点。",
            "runtimeLogs": "运行日志",
            "clear": "清空",
            "noLogs": "暂无日志",
            "noLogsHelp": "连接节点后，内核运行信息会显示在这里。",
            "openApp": "打开 RealityLink",
            "quit": "退出",
            "disconnectQuit": "断开后退出",
            "addNodeFirst": "请先添加节点",
            "switchToNamed": "切换到 %@",
            "connectNamed": "连接 %@"
        ],
        .russian: [
            "language": "Язык",
            "settings": "Настройки",
            "core": "Ядро sing-box",
            "customPath": "Пользовательский путь",
            "corePrompt": "Найти путь Homebrew автоматически",
            "coreHelp": "Если поле пустое, проверяются встроенное ядро, /opt/homebrew/bin и /usr/local/bin.",
            "localProxy": "Локальный прокси",
            "listenPort": "Порт",
            "proxyHelp": "Системный прокси предоставляет HTTP и SOCKS5 на 127.0.0.1.",
            "importLink": "Импорт ссылки",
            "addNode": "Добавить узел",
            "edit": "Изменить",
            "delete": "Удалить",
            "nodesCount": "Узлов: %d",
            "localNodes": "Локальные узлы",
            "renewSubscription": "Обновить подписку",
            "deleteSubscription": "Удалить подписку",
            "deleteSubscriptionTitle": "Удалить эту подписку?",
            "deleteSubscriptionAndNodes": "Удалить подписку и узлы",
            "deleteSubscriptionHelp": "Все узлы этой подписки также будут удалены.",
            "subscriptionUpdateFailed": "Не удалось обновить подписку",
            "testLatency": "Проверить задержку",
            "testGroupLatency": "Проверить эту группу",
            "testLatencyHelp": "Измеряет прямое TCP-подключение через физический сетевой интерфейс.",
            "buyNodes": "Купить узлы",
            "nodeStore": "Сервис узлов",
            "ok": "ОК",
            "page": "Раздел",
            "connection": "Подключение",
            "logs": "Журнал",
            "noNodes": "Узлов пока нет",
            "noNodesHelp": "Импортируйте поддерживаемую ссылку или подписку либо введите параметры вручную.",
            "addManually": "Добавить вручную",
            "server": "Сервер",
            "none": "Нет",
            "fingerprint": "Отпечаток",
            "protocol": "Протокол",
            "security": "Защита",
            "transport": "Транспорт",
            "allowInsecure": "Разрешить недоверенные сертификаты",
            "transportHost": "Заголовок Host",
            "transportPath": "Путь",
            "serviceName": "Имя сервиса",
            "password": "Пароль",
            "encryption": "Шифрование",
            "obfuscation": "Обфускация",
            "obfuscationPassword": "Пароль обфускации",
            "congestionControl": "Контроль перегрузки",
            "udpRelayMode": "Режим UDP relay",
            "connectionMode": "Режим подключения",
            "systemProxy": "Системный прокси",
            "tun": "Глобальный TUN",
            "systemProxyDetail": "Работает с приложениями, использующими настройки прокси macOS; может потребоваться пароль администратора.",
            "tunDetail": "Маршрутизирует большую часть TCP/UDP; после первой авторизации переключение и отключение не требуют пароль повторно.",
            "disconnected": "Отключено",
            "connecting": "Подключение",
            "connected": "Подключено",
            "switching": "Переключение",
            "disconnecting": "Отключение",
            "failed": "Ошибка подключения",
            "trafficThrough": "Трафик идёт через %@",
            "startingCore": "Запуск ядра sing-box",
            "switchingNode": "Переключение узла без изменения сетевых настроек",
            "cleaningNetwork": "Очистка сетевых настроек",
            "checkError": "Проверьте ошибку ниже или откройте журнал",
            "readyToConnect": "Выберите режим и подключитесь",
            "disconnect": "Отключить",
            "switchToNode": "Переключиться на узел",
            "connect": "Подключить",
            "basicInfo": "Основная информация",
            "name": "Название",
            "port": "Порт",
            "publicKey": "Публичный ключ (pbk)",
            "cancel": "Отмена",
            "save": "Сохранить",
            "editNode": "Изменить узел",
            "importVLESS": "Импорт ссылки или подписки",
            "importHelp": "VLESS, VMess, Trojan, Shadowsocks, Hysteria2 и TUIC",
            "pasteClipboard": "Вставить из буфера",
            "import": "Импорт",
            "importing": "Импорт…",
            "subscriptionInvalid": "Ссылка подписки недействительна или не декодируется.",
            "subscriptionScheme": "Поддерживаются только ссылки sub:// и подписки HTTP(S).",
            "subscriptionHTTPError": "Сервер подписки вернул HTTP %d.",
            "subscriptionTooLarge": "Размер ответа подписки превышает 2 МБ.",
            "subscriptionUnreadable": "Ответ подписки не является текстом UTF-8.",
            "subscriptionNoNodes": "Совместимые прокси-узлы в подписке не найдены.",
            "runtimeLogs": "Журнал работы",
            "clear": "Очистить",
            "noLogs": "Журнал пуст",
            "noLogsHelp": "Вывод ядра появится здесь после подключения.",
            "openApp": "Открыть RealityLink",
            "quit": "Выйти",
            "disconnectQuit": "Отключить и выйти",
            "addNodeFirst": "Сначала добавьте узел",
            "switchToNamed": "Переключиться на %@",
            "connectNamed": "Подключить %@"
        ]
    ]
}
